package simpledb;

import java.util.*;

/**
 * The ChunkNestedLoopJoin operator implements the chunk nested loop join operation.
 */
public class ChunkNestedLoopJoin extends Operator {

    private static final long serialVersionUID = 1L;
    private  Chunk chunk;
    private JoinPredicate pred;
    private DbIterator child1, child2;
    private TupleDesc comboTD;
    private int chunkSize;
    int  currentLeftTuple = 0;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     * @param chunkSize
     *            The chunk size used for chunk nested loop join
     */
    public ChunkNestedLoopJoin(JoinPredicate p, DbIterator child1, DbIterator child2, int chunkSize) {
        this.pred = p;
        this.child1 = child1;
        this.child2 = child2;
        this.chunkSize = chunkSize;
        comboTD = TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
        this.chunk = new Chunk(chunkSize);
    }

    public JoinPredicate getJoinPredicate() {
        return pred;
    }

    public TupleDesc getTupleDesc() {
        return comboTD;
    }

    /**
     * Opens the iterator.
     */
    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // IMPLEMENT ME
        super.open();
        child1.open();
        child2.open();
    }

    /**
     * Closes the iterator.
     */
    public void close() {
        // IMPLEMENT ME
        child1.close();
        child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        child2.rewind();
    }

    /**
     * Returns the current chunk. 
     */
    public Chunk getCurrentChunk() throws DbException, TransactionAbortedException {
        // IMPLEMENT ME
        if (chunk == null) {
            chunk = new Chunk(chunkSize);
            chunk.loadChunk(child1);
        }
        return chunk;
    }
 
    /**
     * Updates the current chunk with the next set of Tuples and returns the chunk.
     */
    protected Chunk fetchNextChunk() throws DbException, TransactionAbortedException {
        // IMPLEMENT ME
        if (child1.hasNext()) {
            chunk.loadChunk(child1);
            return chunk;

        }else {
            return  null;
        }
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. 
     * 
     * Note that the tuples returned from this particular implementation
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results.
     * 
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // IMPLEMENT ME

        while (getCurrentChunk() != null){
            Tuple[] tuples = getCurrentChunk().getChunkTuples();
            while (child2.hasNext()){
               Tuple rightTuple = child2.next();
                for (; currentLeftTuple < tuples.length; currentLeftTuple ++) {
                     Tuple leftTuple = tuples[currentLeftTuple];
                    if (pred.filter(leftTuple,rightTuple)){
                        return Tuple.merge(leftTuple, rightTuple);
                    }
                }
                currentLeftTuple = 0;

           }
            child2.rewind();
            fetchNextChunk();

        }
        return null;
    }

    @Override
    public DbIterator[] getChildren() {
        return new DbIterator[] { this.child1, this.child2 };
    }

    @Override
    public void setChildren(DbIterator[] children) {
        this.child1 = children[0];
        this.child2 = children[1];
    }
}
